defaults:
  - _self_

data:
  dataset: yelp
  direction: 1_to_0
  max_size: 200 # Both TAPruning & PromptQuine

model:
  name: "openai-community/gpt2"
  ICL_shots: 1
  ICL_index: 0
  num_devices: 1
  inference_engine: "vLLM" # vllm-Only
  # Decoding parameters
  task_top_k: 1 # Top-k sampling
  num_samples: 1
  # Style classifier parameters
  style_classifier: 'test'
  style_classifier_device_id: 1
  style_batch_size: 256

prompt: # Evaluation-Only
  prompt: ""
  is_pruned_prompt: true 

pruning:
  algorithm: "TAPruning"  # TAPruning | PromptQuine
  fix_prune_order: true
  pruning_order_seed: 0
  TAPruning_threshold: 0.96 # Only TAPruning

prompt_quine: # Default
  initialize_duplicate: false
  min_prompt_length: 15
  max_num_prompts: 10000
  algorithm_mode: "SSGA"
  population_size: 30
  reproduction_size: 50
  # Evaluation-only
  top_percent_rerank: 10
  test_all_elites_for_debug: false
  # Resource Allocation
  successive_halving: true
