defaults:
  - _self_

data:
  dataset: sst-2
  num_shots: 16 # Only PromptQuine
  split: true # Only PromptQuine (num_shots // 2)
  dataset_seed: 0 # Only PromptQuine

model:
  name: "openai-community/gpt2"
  ICL_shots: 1
  ICL_index: 0
  num_devices: 1
  inference_engine: "HF"

prompt: # Evaluation-Only
  prompt: ""
  is_pruned_prompt: true 

pruning:
  algorithm: "TAPruning"  # TAPruning | PromptQuine
  fix_prune_order: true
  pruning_order_seed: 0
  TAPruning_threshold: 0.96 # Only TAPruning
  reward_driven: false

prompt_quine: # Default
  initialize_duplicate: true
  min_prompt_length: 15
  max_num_prompts: 10000
  algorithm_mode: "GGA"
  population_size: 30
  reproduction_size: 50
  # Evaluation-only
  top_percent_rerank: 10
  test_all_elites_for_debug: false





